NguyenHuuKhanhHoang_DOTNET_MVC/NguyenHuuKhanhHoang_DOTNET_MVC/Controllers/NewsDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NguyenHuuKhanhHoang_DOTNET_MVC.Core.Domain.Entity.Comments;
using NguyenHuuKhanhHoang_DOTNET_MVC.Models;
using NguyenHuuKhanhHoang_DOTNET_MVC.Service.Service.News;

namespace NguyenHuuKhanhHoang_DOTNET_MVC.Controllers
{
    public class NewsDetailController : Controller
    {
        INewsService _newsService;
        public NewsDetailController(INewsService newsService)
        {
            _newsService = newsService;
        }
        
        [HttpPost]
        public IActionResult CommentNews(CommentViewModel commentViewModel)
        {
            var request = HttpContext.User.Claims.ToList();
            var a = ViewBag.NewsId;
            string userName = String.Empty;
            long userId = 0;
            if (request.Count > 0)
            {
                ViewBag.UserName = request[0].Value;
                userName= request[0].Value;
                userId = Convert.ToInt64(request[2].Value);
            }
            var comment = new Comment()
            {
                NewsId = Convert.ToInt64(commentViewModel.NewsId),
                NoiDung = commentViewModel.NoiDung,
                UserId = userId,
                UserName = userName
            };
            _newsService.AddComment(comment);
            return RedirectToAction("Index",new {id = commentViewModel.NewsId });
        }
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
        public async Task<IActionResult> Index(long id)
        {
            ViewBag.NewsId = id;
            var request = HttpContext.User.Claims.ToList();
            if (request.Count > 0)
            {
                ViewBag.UserName = request[0].Value;
            }
            var result = await _newsService.GetNewsDetailValue(id);
            var comment = new CommentViewModel();
            return View(comment);
        }
        
    }
}

NguyenHuuKhanhHoang_DOTNET_MVC/NguyenHuuKhanhHoang_DOTNET_MVC/Views/NewsDetail/Index.cshtml
@{
    ViewData["Title"] = "Chi tiet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model CommentViewModel
<section class="section single-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                <div class="page-wrapper">
                    @await Component.InvokeAsync("DetailList", new { id = ViewBag.NewsId })

                    <hr class="invis1">

                    <div class="custombox clearfix">
                        <h4 class="small-title">Bình luận</h4>
                        <div class="row">
                            @*<partial name="_CommentPartialView" />*@
                            <div class="col-lg-12">
                                <form class="form-wrapper" asp-action="CommentNews" asp-controller="NewsDetail" method="POST">
                                    <input type="hidden" asp-for="NewsId" id="custId" value="@ViewBag.NewsId">
                                    <input type="text" class="form-control" placeholder="@ViewBag.UserName" disabled>

                                    <textarea class="form-control" placeholder="Bình luận của bạn" asp-for="NoiDung" id="comment" value="@Model.NoiDung"></textarea>
                                    <span asp-validation-for="NoiDung" style="color:red"></span>
                                    <button type="submit" class="btn btn-primary " id="hoang" disabled>Bình Luận</button>

                                </form>
                            </div>
                        </div>
                    </div>
                </div><!-- end page-wrapper -->
            </div><!-- end col -->

            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                <div class="sidebar">

                </div><!-- end sidebar -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>

@section scripts{
    
    <script type="text/javascript">
        $(document).ready(function(){
          $("#comment").hover(function(){

          },
          function () {
              if ($("#comment").val() != "") {
                  $('#hoang').removeAttr("disabled");
              } else {
                  $('#hoang').prop("disabled", true);
              }
          });
        });
    </script>
}